### ISSUE TITLE
Tests fail when liblzma is built without uncommon filters

### ISSUE THREAD

**Issue by mgorny** [peterjc/backports.lzma#31]
In Gentoo we support a minimal build of xz-utils that includes only the commonly used filters (i.e. CRC32+64, LZMA1+2 and relevant match filters). Sadly, it seems that the tests rely on some less common filters being present and fail in this configuration:

```
======================================================================
ERROR: test_decompressor_raw_2 (__main__.CompressorDecompressorTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/test_lzma.py", line 142, in test_decompressor_raw_2
    lzd = LZMADecompressor(lzma.FORMAT_RAW, filters=FILTERS_RAW_2)
LZMAError: Invalid or unsupported options

======================================================================
ERROR: test_decompressor_raw_3 (__main__.CompressorDecompressorTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/test_lzma.py", line 146, in test_decompressor_raw_3
    lzd = LZMADecompressor(lzma.FORMAT_RAW, filters=FILTERS_RAW_3)
LZMAError: Invalid or unsupported options

======================================================================
ERROR: test_decompressor_raw_4 (__main__.CompressorDecompressorTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/test_lzma.py", line 150, in test_decompressor_raw_4
    lzd = LZMADecompressor(lzma.FORMAT_RAW, filters=FILTERS_RAW_4)
LZMAError: Invalid or unsupported options

======================================================================
ERROR: test_roundtrip_raw (__main__.CompressorDecompressorTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/test_lzma.py", line 199, in test_roundtrip_raw
    lzc = LZMACompressor(lzma.FORMAT_RAW, filters=FILTERS_RAW_4)
LZMAError: Invalid or unsupported options

======================================================================
ERROR: test_decompress_good_input (__main__.CompressDecompressFunctionTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/test_lzma.py", line 313, in test_decompress_good_input
    COMPRESSED_RAW_2, lzma.FORMAT_RAW, filters=FILTERS_RAW_2)
  File "/tmp/portage/dev-python/backports-lzma-0.0.10/work/backports.lzma-0.0.10-pypy/lib/backports/lzma/__init__.py", line 463, in decompress
    decomp = LZMADecompressor(format, memlimit, filters)
LZMAError: Invalid or unsupported options

======================================================================
ERROR: test_roundtrip (__main__.CompressDecompressFunctionTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/test_lzma.py", line 364, in test_roundtrip
    cdata = lzma.compress(INPUT, lzma.FORMAT_RAW, filters=FILTERS_RAW_4)
  File "/tmp/portage/dev-python/backports-lzma-0.0.10/work/backports.lzma-0.0.10-pypy/lib/backports/lzma/__init__.py", line 449, in compress
    comp = LZMACompressor(format, check, preset, filters)
LZMAError: Invalid or unsupported options

======================================================================
ERROR: test_iterator (__main__.FileTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/test_lzma.py", line 823, in test_iterator
    format=lzma.FORMAT_RAW, filters=FILTERS_RAW_2) as f:
  File "/tmp/portage/dev-python/backports-lzma-0.0.10/work/backports.lzma-0.0.10-pypy/lib/backports/lzma/__init__.py", line 113, in __init__
    self._decompressor = LZMADecompressor(**self._init_args)
LZMAError: Invalid or unsupported options

======================================================================
ERROR: test_read (__main__.FileTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/test_lzma.py", line 655, in test_read
    format=lzma.FORMAT_RAW, filters=FILTERS_RAW_2) as f:
  File "/tmp/portage/dev-python/backports-lzma-0.0.10/work/backports.lzma-0.0.10-pypy/lib/backports/lzma/__init__.py", line 113, in __init__
    self._decompressor = LZMADecompressor(**self._init_args)
LZMAError: Invalid or unsupported options

======================================================================
ERROR: test_read_multistream (__main__.FileTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/test_lzma.py", line 694, in test_read_multistream
    format=lzma.FORMAT_RAW, filters=FILTERS_RAW_3) as f:
  File "/tmp/portage/dev-python/backports-lzma-0.0.10/work/backports.lzma-0.0.10-pypy/lib/backports/lzma/__init__.py", line 113, in __init__
    self._decompressor = LZMADecompressor(**self._init_args)
LZMAError: Invalid or unsupported options

======================================================================
ERROR: test_write (__main__.FileTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/test_lzma.py", line 857, in test_write
    filters=FILTERS_RAW_2) as f:
  File "/tmp/portage/dev-python/backports-lzma-0.0.10/work/backports.lzma-0.0.10-pypy/lib/backports/lzma/__init__.py", line 120, in __init__
    preset=preset, filters=filters)
LZMAError: Invalid or unsupported options

----------------------------------------------------------------------
```

I think we should look into more graceful handling of missing liblzma features.

**Comment by peterjc** [comment]
If it is easy to check for these formats at run time, you could preface these tests with a conditional if statement.

**Comment by peterjc** [comment]
Do you know how to determine the available filters at run time?

**Comment by mgorny** [comment]
I'm sorry, I missed your earlier comment.

I don't think there is an easy way of doing that. The way I'd do it would be to capture the exact liblzma error code and catch `LZMA_OPTIONS_ERROR` when constructing.

**Comment by peterjc** [comment]
I'm happy to review and in principle merge a pull request, but don't have easy access to anywhere to test this kind of change.

**Comment by mgorny** [comment]
Ok, I'll try to look at it when I find some time to spare.

**Comment by peterjc** [comment]
I'm about to archive this repository, and so am closing the outstanding issues and pull requests. Thank you for your efforts though.
