### ISSUE TITLE
xz compressed pickled pandas DataFrame does not finish decompressing

### ISSUE THREAD

**Issue by richardkmichael** [peterjc/backports.lzma#43]
Python 2.7.17, installed via pyenv on macOS 10.14.6 with xz via homebrew.

A ~10MB xz compressed (~130MB decompressed) pandas DataFrame does not decompress after waiting at least a minute, clearly in a loop or slow as the machine fans are running at high speed.  htop does not show very much CPU or memory use however.

```bash
$ python --version

Python 2.7.17

$ pip list
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Package         Version
--------------- -------
backports.lzma  0.0.14
numpy           1.16.6
pandas          0.19.2
pip             20.0.2
python-dateutil 2.8.1
pytz            2019.3
setuptools      41.2.0
six             1.14.0

$ python - << "EOP"
import pickle, backports.lzma
with backports.lzma.open('guideseq_data.pkl.xz') as m:
    pickle.load(m)
EOP

^CTraceback (most recent call last):
  File "<stdin>", line 3, in <module>
  File "/Users/testuser/.pyenv/versions/2.7.17/lib/python2.7/pickle.py", line 1384, in load
    return Unpickler(file).load()
  File "/Users/testuser/.pyenv/versions/2.7.17/lib/python2.7/pickle.py", line 863, in load
    key = read(1)
  File "/Users/testuser/.pyenv/versions/2.7.17/lib/python2.7/site-packages/backports/lzma/__init__.py", line 295, in read
    return self._read_block(size)
  File "/Users/testuser/.pyenv/versions/2.7.17/lib/python2.7/site-packages/backports/lzma/__init__.py", line 257, in _read_block
    self._buffer = self._buffer[n:]
KeyboardInterrupt

```

**Comment by peterjc** [comment]
Are you in a position to try this on Python 3 with the standard library version?

**Comment by richardkmichael** [comment]
Yes, but it won't be an *exact* comparison.  pandas `0.19.2` does not install under python 3, and I can't unpickle completely without it.  Using a recent pandas for python 3 means I must use their own backward compat `.read_pickle()`.

I can invoke it several ways, with pandas auto-handling decompression or decompressing around it myself; in both cases it unpickles in ~35s.

Using Python 2.7, as reported, I've waited up to 2 minutes and it does not finish.  I'm not very familiar with performance improvements between 2.7 and 3.7 .. but I guess 4x faster seems unexpected.

Python 3.7.5:

```
$ python << "EOP"
import time, pickle, lzma, pandas
n = 'guideseq_data.pkl.xz'
s = time.time()
with lzma.open(n) as f:
    d = pandas.read_pickle(f, compression=None)
print(time.time() - s)
EOP

36.80446815490723



$ python << "EOP"
import pandas as p
print(p.__version__)
n = 'guideseq_data.pkl.xz'
s = time.time()
d = p.read_pickle(n)
print(time.time() - s)
EOP

'0.24.2'
35.833306074142456
```

**Comment by peterjc** [comment]
OK, that's helpful. Can you deliberately try the backport on the same Python 3 test?

e.g. use``import time, pickle, backports.lzma, pandas`` and then call ``backports.lzma.open``

That will narrow down the problem.

**Comment by richardkmichael** [comment]
Sorry for the delay.

I've tried this on Python 3 with the backport lzma, as below.  After 3 mins (~560MB memory), I stopped it with CTRL-C.  I've included the stack trace below the python.

Regarding the various unpickling errors in the stacktrace:

The pickle contains a pandas `DataFrame` from a different version of pandas (which is incompatible with Python 3, as I mentioned previously). However, it seems that the first error (`ModuleNotFoundError` in this case), should have caused the unpickle to fail, but instead it continued (and went on to encounter several other errors).  All this was happening silently.

So, I probably *can't* unpickle this DataFrame on Python 3 (because of the object incompatibility), but that ought to be separate from the decompression, so that errors are evident.  (I suppose somehow the decompression and unpickling are intertwined, perhaps as chunks..  I have not investigated closely, sorry to punt!)

```
$ python --version
$ python << "EOP"
import time, pickle, backports.lzma, pandas
n = 'guideseq_data.pkl.xz'
s = time.time()
with backports.lzma.open(n) as f:
    d = pandas.read_pickle(f, compression=None)
print(time.time() - s)
EOP

^C
```

Stacktrace:

```
Traceback (most recent call last):
  File "/Users/testuser/lzma/pickle/3/lib/python3.7/site-packages/pandas/io/pickle.py", line 166, in try_read
    return read_wrapper(lambda f: pkl.load(f))
  File "/Users/testuser/lzma/pickle/3/lib/python3.7/site-packages/pandas/io/pickle.py", line 148, in read_wrapper
    return func(f)
  File "/Users/testuser/lzma/pickle/3/lib/python3.7/site-packages/pandas/io/pickle.py", line 166, in <lambda>
    return read_wrapper(lambda f: pkl.load(f))
ModuleNotFoundError: No module named 'pandas.indexes'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/testuser/lzma/pickle/3/lib/python3.7/site-packages/pandas/io/pickle.py", line 173, in try_read
    lambda f: pc.load(f, encoding=encoding, compat=False))
  File "/Users/testuser/lzma/pickle/3/lib/python3.7/site-packages/pandas/io/pickle.py", line 148, in read_wrapper
    return func(f)
  File "/Users/testuser/lzma/pickle/3/lib/python3.7/site-packages/pandas/io/pickle.py", line 173, in <lambda>
    lambda f: pc.load(f, encoding=encoding, compat=False))
  File "/Users/testuser/lzma/pickle/3/lib/python3.7/site-packages/pandas/compat/pickle_compat.py", line 227, in load
    return up.load()
  File "/Users/testuser/.pyenv/versions/3.7.5/lib/python3.7/pickle.py", line 1088, in load
    dispatch[key[0]](self)
  File "/Users/testuser/.pyenv/versions/3.7.5/lib/python3.7/pickle.py", line 1213, in load_string
    self.append(self._decode_string(codecs.escape_decode(data)[0]))
  File "/Users/testuser/.pyenv/versions/3.7.5/lib/python3.7/pickle.py", line 1204, in _decode_string
    return value.decode(self.encoding, self.errors)
UnicodeDecodeError: 'ascii' codec can't decode byte 0x80 in position 1024: ordinal not in range(128)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/testuser/lzma/pickle/3/lib/python3.7/site-packages/pandas/io/pickle.py", line 179, in read_pickle
    return try_read(path)
  File "/Users/testuser/lzma/pickle/3/lib/python3.7/site-packages/pandas/io/pickle.py", line 177, in try_read
    lambda f: pc.load(f, encoding=encoding, compat=True))
  File "/Users/testuser/lzma/pickle/3/lib/python3.7/site-packages/pandas/io/pickle.py", line 148, in read_wrapper
    return func(f)
  File "/Users/testuser/lzma/pickle/3/lib/python3.7/site-packages/pandas/io/pickle.py", line 177, in <lambda>
    lambda f: pc.load(f, encoding=encoding, compat=True))
  File "/Users/testuser/lzma/pickle/3/lib/python3.7/site-packages/pandas/compat/pickle_compat.py", line 227, in load
    return up.load()
  File "/Users/testuser/.pyenv/versions/3.7.5/lib/python3.7/pickle.py", line 1088, in load
    dispatch[key[0]](self)
  File "/Users/testuser/.pyenv/versions/3.7.5/lib/python3.7/pickle.py", line 1213, in load_string
    self.append(self._decode_string(codecs.escape_decode(data)[0]))
  File "/Users/testuser/.pyenv/versions/3.7.5/lib/python3.7/pickle.py", line 1204, in _decode_string
    return value.decode(self.encoding, self.errors)
UnicodeDecodeError: 'ascii' codec can't decode byte 0x80 in position 1024: ordinal not in range(128)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/testuser/lzma/pickle/3/lib/python3.7/site-packages/pandas/io/pickle.py", line 166, in try_read
    return read_wrapper(lambda f: pkl.load(f))
  File "/Users/testuser/lzma/pickle/3/lib/python3.7/site-packages/pandas/io/pickle.py", line 148, in read_wrapper
    return func(f)
  File "/Users/testuser/lzma/pickle/3/lib/python3.7/site-packages/pandas/io/pickle.py", line 166, in <lambda>
    return read_wrapper(lambda f: pkl.load(f))
_pickle.UnpicklingError: unpickling stack underflow

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 5, in <module>
  File "/Users/testuser/lzma/pickle/3/lib/python3.7/site-packages/pandas/io/pickle.py", line 182, in read_pickle
    return try_read(path, encoding='latin1')
  File "/Users/testuser/lzma/pickle/3/lib/python3.7/site-packages/pandas/io/pickle.py", line 173, in try_read
    lambda f: pc.load(f, encoding=encoding, compat=False))
  File "/Users/testuser/lzma/pickle/3/lib/python3.7/site-packages/pandas/io/pickle.py", line 148, in read_wrapper
    return func(f)
  File "/Users/testuser/lzma/pickle/3/lib/python3.7/site-packages/pandas/io/pickle.py", line 173, in <lambda>
    lambda f: pc.load(f, encoding=encoding, compat=False))
  File "/Users/testuser/lzma/pickle/3/lib/python3.7/site-packages/pandas/compat/pickle_compat.py", line 227, in load
    return up.load()
  File "/Users/testuser/.pyenv/versions/3.7.5/lib/python3.7/pickle.py", line 1084, in load
    key = read(1)
  File "/Users/testuser/.pyenv/versions/3.7.5/lib/python3.7/pickle.py", line 265, in read
    return self.file_read(n)
  File "/Users/testuser/lzma/pickle/3/lib/python3.7/site-packages/backports/lzma/__init__.py", line 295, in read
    return self._read_block(size)
  File "/Users/testuser/lzma/pickle/3/lib/python3.7/site-packages/backports/lzma/__init__.py", line 257, in _read_block
    self._buffer = self._buffer[n:]
KeyboardInterrupt
```

**Comment by peterjc** [comment]
Sharing pickles between Python 2 and 3 is likely to fail due to different import paths, so that likely explains the ``ModuleNotFoundError``.

I was assuming you had a pickle created under Python 3 which can be loaded under Python 3, and then you applied xz compression to it, and tested loading with the standard library ``lzma`` versus the backports.

**Comment by peterjc** [comment]
I'm about to archive this repository, and so am closing the outstanding issues and pull requests. Thank you for your efforts though.
