### ISSUE TITLE
PyPy support

### ISSUE THREAD

**Issue by peterjc** [peterjc/backports.lzma#5]
PyPy was (?) working according to discussion on #2, but appears to be broken again, e.g.

```
$ pypy2.3 test_lzma.py
...
test_simple_bad_args (__main__.CompressorDecompressorTestCase) ... ok
test_bad_args (__main__.CompressDecompressFunctionTestCase) ... ERROR
test_decompress_bad_input (__main__.CompressDecompressFunctionTestCase) ... ok
...

======================================================================
ERROR: test_bad_args (__main__.CompressDecompressFunctionTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/test_lzma.py", line 269, in test_bad_args
    b"", format=lzma.FORMAT_RAW, filters={})
  File "/Users/pjcock/Downloads/Software/pypy-2.3-osx64/lib-python/2.7/unittest/case.py", line 475, in assertRaises
    callableObj(*args, **kwargs)
  File "/Users/pjcock/Downloads/Software/pypy-2.3-osx64/site-packages/backports/lzma/__init__.py", line 457, in decompress
    decomp = LZMADecompressor(format, memlimit, filters)
LZMAError: Internal error

----------------------------------------------------------------------
Ran 94 tests in 7.147s

FAILED (errors=1)
Traceback (most recent call last):
  File "app_main.py", line 75, in run_toplevel
  File "test/test_lzma.py", line 1571, in <module>
    test_main()
  File "test/test_lzma.py", line 1567, in test_main
    MiscellaneousTestCase,
  File "/Users/pjcock/Downloads/Software/pypy-2.3-osx64/lib-python/2.7/test/test_support.py", line 1261, in run_unittest
    _run_suite(suite)
  File "/Users/pjcock/Downloads/Software/pypy-2.3-osx64/lib-python/2.7/test/test_support.py", line 1215, in _run_suite
    raise TestFailed(err)
TestFailed: Traceback (most recent call last):
  File "test/test_lzma.py", line 269, in test_bad_args
    b"", format=lzma.FORMAT_RAW, filters={})
  File "/Users/pjcock/Downloads/Software/pypy-2.3-osx64/lib-python/2.7/unittest/case.py", line 475, in assertRaises
    callableObj(*args, **kwargs)
  File "/Users/pjcock/Downloads/Software/pypy-2.3-osx64/site-packages/backports/lzma/__init__.py", line 457, in decompress
    decomp = LZMADecompressor(format, memlimit, filters)
LZMAError: Internal error
```

**Comment by mgorny** [comment]
Let's continue the discussion on PyPy here since this test failure report is still 100% relevant.

To update the line numbers:
```
ERROR: test_bad_args (__main__.CompressDecompressFunctionTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/test_lzma.py", line 273, in test_bad_args
    b"", format=lzma.FORMAT_RAW, filters={})
  File "/usr/lib64/pypy/lib-python/2.7/unittest/case.py", line 473, in assertRaises
    callableObj(*args, **kwargs)
  File "/home/mgorny/git/backports.lzma/build/lib.linux-x86_64-2.7/backports/lzma/__init__.py", line 463, in decompress
    decomp = LZMADecompressor(format, memlimit, filters)
LZMAError: Internal error
```

I've confirmed this with the most recent PyPy and determined that it applies to old versions as well. FWICS, commenting this specific assert out makes the tests pass, so no other line fails this way. Now, if I try this call with CPython 2.7, I get:

```
Traceback (most recent call last):
  File "test/test_lzma.py", line 273, in test_bad_args
    b"", format=lzma.FORMAT_RAW, filters={})
  File "/home/mgorny/git/backports.lzma/build/lib.linux-x86_64-2.7/backports/lzma/__init__.py", line 463, in decompress
    decomp = LZMADecompressor(format, memlimit, filters)
TypeError: object of type 'dict' has no len()
```

For comparison, PyPy gives:
```
Traceback (most recent call last):
  File "test/test_lzma.py", line 273, in test_bad_args
    b"", format=lzma.FORMAT_RAW, filters={})
  File "/home/mgorny/git/backports.lzma/build/lib.linux-x86_64-2.7/backports/lzma/__init__.py", line 463, in decompress
    decomp = LZMADecompressor(format, memlimit, filters)
LZMAError: Internal error
```

So my guess would be that CPython raises `TypeError` when calling `PySequence_Length()` on `dict` and PyPy doesn't consider this an error.

**Comment by mgorny** [comment]
And to be honest, this seems to a bug in CPython. FWICS, `dict` doesn't implement the sequence protocol and `PySequence_Check()` returns 0 for it both in CPython and PyPy. However, `PySequence_Length()` is documented as:

> Returns the number of objects in sequence o on success, and -1 on failure. **For objects that do not provide sequence protocol, this is equivalent to the Python expression len(o).**

(highlight mine)

So according to the documentation, it should return `len({})`, i.e. 0. That's what PyPy does. CPython on the other hand claims that `object of type 'dict' has no len()` which seems incorrect.

**Comment by mgorny** [comment]
Congratulations, we have round issue number: https://bugs.python.org/issue32500 ;-)

**Comment by peterjc** [comment]
OK, v0.0.10 is up on PyPy which should fix this - thank you to @mgorny 
https://pypi.python.org/pypi/backports.lzma/0.0.10
